### ISSUE TITLE
Use secret instead of configmap for mlflow authentication

### ISSUE THREAD

**Issue by odysseu** [InseeFrLab/helm-charts-automation#54]
We should use secret instead of configmap for mlflow authentication.

TODO
- This file https://github.com/InseeFrLab/helm-charts-automation/blob/master/charts/mlflow/templates/configmap-mlflow-auth.yaml should be secret-auth.yml
- bump version

**Comment by ihiverlet** [comment]
It's done [here](https://github.com/InseeFrLab/helm-charts-automation/commit/a7259d85d3a0a97dabc07b5c3aca05478ed9eb9a)

**Comment by ihiverlet** [comment]
It's done [here](https://github.com/InseeFrLab/helm-charts-automation/commit/a7259d85d3a0a97dabc07b5c3aca05478ed9eb9a)
